name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          brew install opencv@4 ffmpeg@5 fftw sqlite spdlog
          brew link ffmpeg@5
          brew install googletest google-benchmark

      - name: Make vhash
        run: |
          make dev

      - name: Test vhash
        run: |
          make test
